* Minor syntax adjustment of ndiswrapper script. Use exec to fork the      ndiswrapper action from shell and a more descriptive shell variable for      latest ndisrwapper util version. [debian/ndiswrapper]    * Rewrite loadndisdriver script to allow processing of -v (version) query.      Function borrowed from debian/ndiswrapper to locate the latest binary to      pass the -v argument to. [debian/loadndisdriver]    * Use exec to fork loadndiswrapper action from current shell, add a comment      in there so that possible arguments to loadndiswrapper from the      ndiswrapper module are not forgotten. [debian/loadndisdriver]

diff --git a/debian/loadndisdriver b/debian/loadndisdriver
--- a/debian/loadndisdriver
+++ b/debian/loadndisdriver
@@ -2,9 +2,23 @@
 
 set -e
 
-if [ -z "$3" ]; then
-	echo "Error: no version specified!" 1>&2
-	exit 1
-fi
+latest_loadndisdriver () {
+        for file in /sbin/loadndisdriver-[\.0-9][\.0-9]*; do
+                echo $file
+        done | sort -n -t - -k 2 | tail -1
+}
 
-/sbin/loadndisdriver-$3 "$@"
+if [ "$#" -ge "3" ]; then
+	# /sbin/loadndisdriver <ioctl command> <debug value> <utils version> \
+	#	<vendor> <device> <subdevice> <subvendor> <bus>
+	exec /sbin/loadndisdriver-$3 "$@"
+elif [ "$1" = "-v" ]; then
+	# report version number of most recent loadndisdriver binary
+	LOADNDISDRIVER=$(latest_loadndisdriver)
+	if [ -x "$LOADNDISDRIVER" ]; then
+		exec $LOADNDISDRIVER -v
+	else
+		echo "Error: unable to find latest loadndisdriver!" 1>&2
+		exit 1
+	fi
+fi
diff --git a/debian/ndiswrapper b/debian/ndiswrapper
--- a/debian/ndiswrapper
+++ b/debian/ndiswrapper
@@ -8,12 +8,11 @@ latest_ndiswrapper () {
 	done | sort -n -t - -k 2 | tail -1
 }
 
-unset LATEST
-LATEST=`latest_ndiswrapper`
 
-if [ -x "$LATEST" ]; then
-	$LATEST "$@"
+NDISWRAPPER=$(latest_ndiswrapper)
+if [ -x "$NDISWRAPPER" ]; then
+	exec $NDISWRAPPER "$@"
 else
-	echo "Error: no versions of ndiswrapper found!" 1>&2
+	echo "Error: no ndiswrapper utils found!" 1>&2
 	exit 1
 fi
